version: '3.3'

services:

  mariadb:
    build: ./docker/mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      # - ./docker/database/data:/var/lib/mysql
      - data:/var/lib/mysql
      - ./docker/database/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/database/mysql-slow.log:/var/log/mysql/mysql-slow.log
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"


  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - "${PROJECT_ROOT}:/var/www/html"
      # - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/conf.d/grouper.dev.conf:/etc/nginx/conf.d/grouper.dev.conf
    networks:
      - server
    depends_on:
      - app
    environment:
      - NGINX_HOST=grouper.dev
      - NGINX_PORT=80
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec
    # command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/web.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"


  app:
    build: ./docker/php
    expose:
      - 9000
    volumes:
      - "${PROJECT_ROOT}:/var/www/html"
    # working_dir: /var/www/html/public
    restart: always
    networks:
      - database
      - server
      - cache
    depends_on:
      - mariadb


  redis:
    build: ./docker/redis
    expose:
      - 6379
    volumes:
      - cache:/data
      # - redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - server
      - cache


volumes:
  data:
  cache:

networks:
  database:
  server:
  cache: