version '3.3'

services:

  mariadb:
    build: ./docker/mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker/database/data:/var/lib/mysql
      # - data:/var/lib/mysql
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"


  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - "${PROJECT_ROOT}:/var/www/html"
      # - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - server
    # environment:
    #   - NGINX_HOST=grouper.dev
    #   - NGINX_PORT=80
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec


  php:
    build: ./docker/php
    expose:
      - 9000
    volumes:
      - "${PROJECT_ROOT}:/var/www/html"
    restart: always
    networks:
      - database
      - server
      - cache
    depends_on:
      - nginx
      - mariadb


    redis:
      build: ./docker/redis
      expose:
        - 6379
      volumes:
        - cache:/data
        # - redis.conf:/usr/local/etc/redis/redis.conf
      networks:
        - server
        - cache


volumes:
  data:
  cache:

networks:
  database:
  server:
  cache: